modLoader="javafml"
loaderVersion="[52,)"
license="CC0-1.0"

[[mods]]
modId="cinemarr"
version="${version}"
displayName="Cinemarr"
logoFile="cinemarr.png"
authors="stonytark_mkii"
displayTest="MATCH_VERSION"
description='''Streams shared, synchronized Plex video to in-world television screens.'''

[[dependencies.cinemarr]]
modId="forge"
mandatory=true
versionRange="[52.1.16,53)"
ordering="NONE"
side="BOTH"

[[dependencies.cinemarr]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"
