license="CC0-1.0"

[[mods]]
modId="cinemarr"
version="${version}"
displayName="Cinemarr"
logoFile="cinemarr.png"
authors="stonytark_mkii"
description='''Streams shared, synchronized Plex video to in-world television screens.'''

[[mixins]]
config="cinemarr.mixins.json"

[[dependencies.cinemarr]]
modId="neoforge"
type="required"
versionRange="[26.1.2.97,26.1.3)"
ordering="NONE"
side="BOTH"

[[dependencies.cinemarr]]
modId="minecraft"
type="required"
versionRange="[26.1.2,26.2)"
ordering="NONE"
side="BOTH"
