modLoader="javafml"
loaderVersion="[65,66)"
license="CC0-1.0"

[[mods]]
modId="cinemarr"
version="${version}"
displayName="Cinemarr"
logoFile="cinemarr.png"
authors="stonytark_mkii"
displayTest="MATCH_VERSION"
description='''Streams shared, synchronized Plex video to in-world television screens.'''

[[dependencies.cinemarr]]
modId="forge"
mandatory=true
versionRange="[65,66)"
ordering="NONE"
side="BOTH"

[[dependencies.cinemarr]]
modId="minecraft"
mandatory=true
versionRange="[26.2,26.3)"
ordering="NONE"
side="BOTH"
