#!/usr/bin/env python3
"""Reduce native cores to stack traces; raw process memory is never uploaded."""
import argparse
from pathlib import Path
import re
import subprocess


def stack_text(text):
    # GDB's automatic core banner can contain the original command line.
    return '\n'.join(line for line in text.splitlines()
                     if not line.startswith('Core was generated by ')) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('directory', type=Path)
    args = parser.parse_args()
    for core in sorted(args.directory.glob('core.*')):
        if not core.is_file() or core.suffix == '.txt':
            continue
        report = core.with_name(core.name + '.backtrace.txt')
        with report.open('w') as output:
            try:
                mappings = subprocess.run(
                    ['gdb', '--batch', '-iex', 'set debuginfod enabled off',
                     '-c', str(core), '-ex', 'info proc mappings'],
                    stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, timeout=45)
                # NT_FILE mappings identify the exact launcher, including its JDK.
                executables = re.findall(r'(/[^\s]+/bin/java)\s*$', mappings.stdout, re.MULTILINE)
                executable = next((p for p in executables if Path(p).is_file()), None)
                if executable is None:
                    output.write('Could not resolve original Java executable.\n')
                    output.write(stack_text(mappings.stdout))
                    continue
                output.write('Original executable: ' + executable + '\n')
                output.flush()
                trace = subprocess.run(['gdb', '--batch', '-iex', 'set debuginfod enabled off',
                                '-iex', 'set print frame-arguments none',
                                executable, str(core),
                                '-ex', 'set pagination off',
                                '-ex', 'thread apply all bt',
                                '-ex', 'info sharedlibrary'],
                               stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                               text=True, timeout=90)
                output.write(stack_text(trace.stdout))
            except subprocess.TimeoutExpired:
                output.write('\nNative stack collection reached its time limit.\n')


if __name__ == '__main__':
    main()
