package stonytark.cinemarr.network;

import net.minecraft.network.RegistryFriendlyByteBuf;
import net.minecraft.network.codec.StreamCodec;
import net.minecraft.network.protocol.common.custom.CustomPacketPayload;
import net.minecraft.resources.Identifier;
import stonytark.cinemarr.Cinemarr;
import stonytark.cinemarr.core.protocol.CinemarrMessage;

/** Connection negotiation and media-clock messages shared by the television protocol. */
public final class CinemarrPayloads {
    private static <T extends CustomPacketPayload> CustomPacketPayload.Type<T> genericType(String path){return new CustomPacketPayload.Type<>(Identifier.fromNamespaceAndPath(Cinemarr.MODID,path));}
    public record ClientHello(int protocolVersion) implements CustomPacketPayload,CinemarrMessage{public static final Type<ClientHello> TYPE=genericType("client_hello");public static final StreamCodec<RegistryFriendlyByteBuf,ClientHello> CODEC=StreamCodec.ofMember(ClientHello::write,ClientHello::read);private void write(RegistryFriendlyByteBuf b){b.writeVarInt(protocolVersion);}private static ClientHello read(RegistryFriendlyByteBuf b){return new ClientHello(b.readVarInt());}@Override public Type<? extends CustomPacketPayload> type(){return TYPE;}}
    public record ServerHello(int protocolVersion,long serverEpochMs) implements CustomPacketPayload,CinemarrMessage{public static final Type<ServerHello> TYPE=genericType("server_hello");public static final StreamCodec<RegistryFriendlyByteBuf,ServerHello> CODEC=StreamCodec.ofMember(ServerHello::write,ServerHello::read);private void write(RegistryFriendlyByteBuf b){b.writeVarInt(protocolVersion);b.writeLong(serverEpochMs);}private static ServerHello read(RegistryFriendlyByteBuf b){return new ServerHello(b.readVarInt(),b.readLong());}@Override public Type<? extends CustomPacketPayload> type(){return TYPE;}}
    public record TimeSyncRequest(long nonce,long clientSentEpochMs) implements CustomPacketPayload,CinemarrMessage{public static final Type<TimeSyncRequest> TYPE=genericType("time_sync_request");public static final StreamCodec<RegistryFriendlyByteBuf,TimeSyncRequest> CODEC=StreamCodec.ofMember(TimeSyncRequest::write,TimeSyncRequest::read);private void write(RegistryFriendlyByteBuf b){b.writeLong(nonce);b.writeLong(clientSentEpochMs);}private static TimeSyncRequest read(RegistryFriendlyByteBuf b){return new TimeSyncRequest(b.readLong(),b.readLong());}@Override public Type<? extends CustomPacketPayload> type(){return TYPE;}}
    public record TimeSyncResponse(long nonce,long clientSentEpochMs,long serverEpochMs) implements CustomPacketPayload,CinemarrMessage{public static final Type<TimeSyncResponse> TYPE=genericType("time_sync_response");public static final StreamCodec<RegistryFriendlyByteBuf,TimeSyncResponse> CODEC=StreamCodec.ofMember(TimeSyncResponse::write,TimeSyncResponse::read);private void write(RegistryFriendlyByteBuf b){b.writeLong(nonce);b.writeLong(clientSentEpochMs);b.writeLong(serverEpochMs);}private static TimeSyncResponse read(RegistryFriendlyByteBuf b){return new TimeSyncResponse(b.readLong(),b.readLong(),b.readLong());}@Override public Type<? extends CustomPacketPayload> type(){return TYPE;}}
    public record ErrorMessage(String message) implements CustomPacketPayload,CinemarrMessage{public static final Type<ErrorMessage> TYPE=genericType("error");public static final StreamCodec<RegistryFriendlyByteBuf,ErrorMessage> CODEC=StreamCodec.ofMember(ErrorMessage::write,ErrorMessage::read);public ErrorMessage{message=message==null?"":message.substring(0,Math.min(message.length(),256));}private void write(RegistryFriendlyByteBuf b){b.writeUtf(message,256);}private static ErrorMessage read(RegistryFriendlyByteBuf b){return new ErrorMessage(b.readUtf(256));}@Override public Type<? extends CustomPacketPayload> type(){return TYPE;}}
    private CinemarrPayloads(){}
}
